# Один домен на строку!

# Госуслуги
gosuslugi.ru
esia.gosuslugi.ru
gu-st.ru
sfd.gosuslugi.ru
lk.gosuslugi.ru
# для правильной работы геопозиции
mc.yandex.ru


# Озон
ozon.ru

# AVITO
avito.ru

job.rt.ru
dzen.ru
vk.com
profi.ru